---
controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true
    # Controllers for each revolute joint
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
     

joint_trajectory_controller:
  ros__parameters:
    joints:
      - hip1_fl
      - hip1_fr
      - hip1_br
      - hip1_bl
      - hip2_bl
      - hip2_br
      - hip2_fl
      - hip2_fr
      - knee_fr
      - knee_fl
      - knee_bl
      - knee_br

      
     
    allow_nonzero_velocity_at_trajectory_end: false
    interface_name: position
    command_interfaces:
      - position  # Ensure position is listed here if it's the interface you intend to control
    state_interfaces:
      - position
      - velocity
     
    # constraints:
    #   goal_time: 0.5
    #   stopped_velocity_tolerance: 0.01
    #   trajectory_execution:
    #     execution_duration: 1.0
    #     velocity_scaling: 1.0


      # FR1_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FR1_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
  
      # FR2_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FR2_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
  
      # FR3_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FR3_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
  
      # FR4_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FR4_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
        
  
      # FL1_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FL1_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
      # FL2_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FL2_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
      # FL3_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FL3_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
  
      # FL4_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: FL4_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
       
      # RR1_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RR1_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
  
      # RR2_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RR2_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
      # RR3_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RR3_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #     - position
      #     - velocity
      #     - effort
  
      # RR4_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RR4_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interface: position
  
      # RL1_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RL1_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
  
      # RL2_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RL2_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
      # RL3_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RL3_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interfaces:
      #   - position
      #   - velocity
      #   - effort
  
      # RL4_joint_controller:
      #   type: effort_controllers/JointPositionController
      #   joint: RL4_joint
      #   pid:
      #     p: 100.0
      #     i: 1.0
      #     d: 10.0
      #     i_max: 1.0
      #     i_min: -1.0
      #   command_interface: position
      #   state_interface: position
  
  